version: "3"
services:
  databasemaster:
    image: mysql:debian
    container_name: "databasemaster"
    ports:
      - 3326:3306
    volumes:
      - ./sql/init2.sql:/docker-entrypoint-initdb.d/init2.sql
      - ./sql/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./sql/stored_procedures.sql:/docker-entrypoint-initdb.d/stored_procedures.sql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=ALMACEN
      
 